apiVersion: batch/v1
kind: Job
metadata:
  name: somejob
spec:
  template:
    spec:
      containers:
      - name: somejob
        image: busybox
        command: ["sleep","60"]
      restartPolicy: Never
  backoffLimit: 0