apiVersion: batch/v1
kind: Job
metadata:
  name: somejob
  annotations:
    argocd.argoproj.io/sync-wave: '{{ .Values.tenant.sync.wave }}'
spec:
  template:
    spec:
      containers:
      - name: somejob
        image: busybox
        command: ["sleep","60"]
      restartPolicy: Never
  backoffLimit: 0