apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: idp-apps-{{ .Release.Namespace }}
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.configuration.git }}
        revision: HEAD
{{- .Values.configuration.paths | toYaml | nindent 8 }}
  template:
    metadata:
      name: 'idp-apps-{{ .Release.Namespace }}-{{ "{{tenant.chart}}" }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ "{{tenant.sync.wave}}" }}'
    spec:
      project: {{ .Release.Namespace }}
      source:
        repoURL: {{ .Values.app.git }}
        targetRevision: HEAD
        path: 'charts/{{ "{{tenant.chart}}" }}'
        helm:
          valueFiles:
            - '{{ "{{self}}" }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: {{ .Release.Namespace }}
      operation:
        syncStrategy:
          apply:
            force: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Replace=true
          - CreateNamespace=true
