apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-{{ .Values.tenant.namespace }}
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: {{ .Values.configuration.git }}
        revision: HEAD
{{- .Values.configuration.paths | toYaml | nindent 8 }}
  template:
    metadata:
      name: 'apps-{{ .Values.tenant.namespace }}-{{ "{{tenant.chart}}" }}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ "{{tenant.sync.wave}}" }}'
    spec:
      project: '{{ "{{tenant.project}}" }}'
      source:
        repoURL: {{ .Values.app.git }}
        targetRevision: HEAD
        path: 'charts/{{ "{{tenant.chart}}" }}'
        helm:
          valueFiles:
            - '{{ "{{self}}" }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{tenant.namespace}}" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Replace=true
          - CreateNamespace=true
